DESCRIPTION = "Chromium is an open-source browser project that aims to build a safer, faster, and more stable way for all users to experience the web."
HOMEPAGE = "https://www.chromium.org/Home"
SRC_URI = "https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${PV}.tar.xz"

LICENSE = "BSD-3-Clause"

LIC_FILES_CHKSUM = "\
    file://${S}/LICENSE;md5=0fca02217a5d49a14dfe2d11837bb34d \
    "

SRC_URI[md5sum] = "08b9d32397aacb75f6d1911df3204116"
SRC_URI[sha256sum] = "df89c284b0109566acc6a5a1a84d94a5ab0509cc3a86a31299a50328991edcde"
